name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: try multiple message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          ⚡️ <a href="https://github.com/LyhourChhen/enhance-antd-table/commit/${{ github.event.push.after }}">Commits</a> had some change, pls make pull request.
          By <em>${{ github.event.push.pusher.name }} </em><b>@${{ github.actor }}</b> ⚡️
          COMMIT: <b>${{ github.event.head_commit.message }}</b>
          
